stages: 
 prepare: 
   cmd: echo "Verificando que los datos existen..." 
   deps: 
     - data/breast_cancer.csv 
 train: 
   cmd: python3 train.py --n_estimators ${train.n_estimators} 
   deps: 
     - train.py 
     - requirements.txt 
     - data/breast_cancer.csv 
   outs: 
     - model.pkl 
     - confusion_matrix.png 
   metrics: 
     - mlflow_metrics.json 
   params: 
     - train.n_estimators 