apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring 
metadata: 
  name: mlops-api-pf-pod-monitor 
  namespace: default
spec:  
  selector: 
    matchLabels: 
      app: mlops-api-pf  
  endpoints: 
    - port: metrics 
      path: /metrics 
      interval: 30s